@echo off
echo Starting Todo App Backend...
cd backend
call venv\Scripts\activate
echo Installing dependencies...
pip install -r requirements.txt
echo Starting FastAPI server...
uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
